name: Rename Title

on:
  pull_request:
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: rename PR title
        with:
          route: POST /repos/Zico3637/django_local_library/pull/2
          title: New title
