name: Rename Title

on:
  pull_request:
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get_context
        with:
          script: console.log(context)

      - uses: actions/github-script@v6
        id: rename_pr_title
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: "New Title 2",
            })
