name: Rename Title

on:
  pull_request:
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        id: run_tests
        run: |
          echo "ABC=ABC" >> $GITHUB_OUTPUT
          echo "XYZ=XYZ" >> $GITHUB_OUTPUT
          
      - uses: actions/github-script@v6
        id: rename_pr_title
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: '${"ABC XYZ New Title 2"/"ABC"/"F${{steps.run_tests.outputs.ABC}}"}',
            })
