name: Rename Title

on:
  pull_request:
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: rename_pr_title
        with:
          script: console.log(context)
